name: ci
on:
    push:
      branches:
        - '**'
      tags-ignore:
        - v*
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run precommit
          run: |
          sudo apt-get install -y cmake
          make precommit_docker
